version: '3.8'

services:
  dev:
    command: /bin/bash -c "
      ./usr/opt/db_seeder/run_application_setup.sh
      "
    container_name: db_seeder_dev
    image: konnexionsgmbh/db_seeder:latest
    networks:
      - net
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Transfer:/Transfer_db_seeder

networks:
  net:
