copyright: Copyright &copy;2020-2022, Konnexions GmbH.

edit_uri: ""

extra:
  generator: false
extra_css:
  - assets/pymdownx-extras/extra-b1466b3f51.css
extra_javascript:
  - https://unpkg.com/mermaid@8.13.3/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/pymdownx-extras/extra-loader-9e2c67b9.js

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - toc : {
    toc_depth: "1-3"
  }

nav:
  - Home: index.md
  - Release Documents:
    - Release Notes: release_notes.md
    - Release History: release_history.md
    - Release Schedule: release_schedule.md
  - Code of Conduct: code_of_conduct.md
  - Contributing Guide: contributing.md
  - License: license.md

plugins:
  - autorefs
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 3
            paths: [src/io_avstats]
            show_root_heading: false
            show_source: true
  - search

repo_name: GitHub
repo_url: https://github.com/KonnexionsGmbH/db_seeder/

site_name: DBSeeder - Relational Database Data Generator
site_url: https://www.konnexions.ch/
site_description: Relational Database Data Generator
site_author: Konnexions GmbH Team

theme:
  favicon: img/Icon.png
  features:
    - search.highlight
    - search.suggest
  language: en
  logo: img/Logo.png
  name: material
  palette:
    primary: blue
    accent: red
