# Ubuntu 20.04 Focal Fossa
FROM ubuntu:20.04 as base

# Setting Environment Variables ------------------------------------------------
ARG APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=false
ARG DEBIAN_FRONTEND=noninteractive
ARG LOCALE=en_US.UTF-8
ARG TIMEZONE=Europe/Zurich

ARG VERSION_JAVA=14.0.2
ARG VERSION_PRESTO=339

# Supplement necessary system software -----------------------------------------
RUN apt-get update \
 && apt-get install -qy \
 && apt-get dist-upgrade -qy

RUN apt-get install -qy apt-utils \
                        iputils-ping \
                        language-pack-de \
                        less \
                        lsb-core \
                        net-tools \
                        wget

# Setting Locale & Timezone ----------------------------------------------------
RUN ln -fs /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
 && apt-get install -qy tzdata \
 && dpkg-reconfigure --frontend noninteractive tzdata

RUN locale-gen "${LOCALE}" \
 && dpkg-reconfigure locales

ENV LANG=${LOCALE} \
    LANGUAGE=${LOCALE} \
    LC_ALL=${LOCALE}

# Java -------------------------------------------------------------------------
RUN wget --quiet https://download.java.net/java/GA/jdk${VERSION_JAVA}/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-${VERSION_JAVA}_linux-x64_bin.tar.gz \
 && tar -xf openjdk-${VERSION_JAVA}_linux-x64_bin.tar.gz \
 && mv jdk-${VERSION_JAVA} /opt/
 
ENV JAVA_HOME=/opt/jdk-${VERSION_JAVA}
ENV PATH="$JAVA_HOME/bin:${PATH}"    

# presto - Server --------------------------------------------------------------
RUN wget --quiet https://repo1.maven.org/maven2/io/prestosql/presto-server/${VERSION_PRESTO}/presto-server-${VERSION_PRESTO}.tar.gz \
 && tar -xf presto-server-*.tar.gz \
 && mv presto-server-${VERSION_PRESTO} presto-server \
 && mkdir presto-server/etc \
 && mkdir presto-server/etc/catalog
 
COPY presto/base/* /presto-server/etc/
COPY presto/catalog/* /presto-server/etc/catalog/

# presto - Command-Line Interface ----------------------------------------------
RUN wget --quiet https://repo1.maven.org/maven2/io/prestosql/presto-cli/${VERSION_PRESTO}/presto-cli-${VERSION_PRESTO}-executable.jar \
 && mv presto-cli-${VERSION_PRESTO}-executable.jar /presto-server/bin/presto \
 && chmod +x /presto-server/bin/presto

ENV PATH=/presto-server/bin/:${PATH}

# Python -----------------------------------------------------------------------
RUN apt-get install -qy python3 \
 && apt-get install -qy python3-venv \
 && ln -s /usr/bin/python3 /usr/bin/python \
 && wget --quiet https://bootstrap.pypa.io/get-pip.py
 
ENV PATH=/presto-server/bin/:${PATH}

# Cleanup ----------------------------------------------------------------------
RUN rm -f *.gz

RUN echo "=====================================================================> Curent Date: " \
 && date \
# Show Environment Variables ---------------------------------------------------
 && echo "=====================================================================> Environment variable LANG: " \
 && echo $LANG \
 && echo "=====================================================================> Environment variable LANGUAGE: " \
 && echo $LANGUAGE \
 && echo "=====================================================================> Environment variable LC_ALL: " \
 && echo $LC_ALL \
 && echo "=====================================================================> Environment variable PATH: " \
 && echo $PATH \
# Show component versions ------------------------------------------------------
 && echo "=====================================================================> Version  ubuntu: " \
 && lsb_release -a \
 && echo "=====================================================================> Version  java: " \
 && java -version \
 && echo "=====================================================================> Version  python3: " \
 && python3 --version \
 && echo "=====================================================================> Version  wget: " \
 && wget --version 

EXPOSE 8080

CMD ["presto-server/bin/launcher", "run"] 
ping -n 10 127.0.0.1 >nul
