name: Continuous Integration - Ubuntu

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

env:
  DB_SEEDER_FILE_JSON_NAME: resources/json/db_seeder_schema:company_50.json
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  standards:
    # --------------------------------------------------------------------------
    # Perform all development-specific tools, including formatting, static code
    # analysis, style enforcement and documentation creation. Changes in the code
    # or in the documentation are also replicated in the repository.
    # --------------------------------------------------------------------------
    name: OS ${{ matrix.os }} - Python ${{ matrix.python-version }} - Development Standards
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: ["ubuntu-20.04"]
        java-version: ["17"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'gradle'
      - name: Compiling the project
        run: gradle copyJarToLib
      - name: Generating the schema
        run: ./scripts/run_db_seeder_generate_schema.sh
      - name: Run H2 Database Engine - Client
        run: ./run_db_seeder.sh h2               yes 1
      - name: Run H2 Database Engine - Embedded
        run: ./run_db_seeder.sh h2_emb           yes 1
      - name: Run PostgreSQL - Client
        run: ./run_db_seeder.sh postgresql       yes 1
      - name: Run PostgreSQL - trino
        run: ./run_db_seeder.sh postgresql_trino yes 1
