name: Continuous Integration - Windows

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

env:
  DB_SEEDER_FILE_JSON_NAME: resources\json\db_seeder_schema.company_50.json
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  standards:
    # --------------------------------------------------------------------------
    # Test of a few selected databases..
    # --------------------------------------------------------------------------
    name: OS ${{ matrix.os }} - Java ${{ matrix.java-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: ["windows-2019", "windows-2022"]
        java-version: ["16", "17"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'gradle'
      - name: Compiling the project
        run: gradle copyJarToLib
      - name: Generating the schema
        run: scripts\run_db_seeder_generate_schema.bat
        shell: cmd
      - name: Run H2 Database Engine - Client
        run: run_db_seeder.bat h2               yes 1
        shell: cmd
      - name: Run H2 Database Engine - Embedded
        run: run_db_seeder.bat h2_emb           yes 1
        shell: cmd
      - name: Run PostgreSQL - Client
        run: run_db_seeder.bat postgresql       yes 1
        shell: cmd
      - name: Run PostgreSQL - trino
        run: run_db_seeder.bat postgresql_trino yes 1
        shell: cmd
